# fly.toml app configuration file generated for henzworld on 2025-08-30T12:51:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'henzworld'
primary_region = 'ord'

[build]
[build.args]
GO_VERSION = '1.24.5'

[env]
PORT = '8000'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
